name: Auto Update Submodule in Websites-1

on:
  push:
    branches:
      - main  # or your plugin's main branch

jobs:
  update-websites:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout plugin repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name "Sagar Savani"
          git config --global user.email "sagar.savani@multidots.com"
      
      - name: Fetch deploy sites from API
        id: fetch_sites
        run: |
          echo "Fetching site list from API..."
          SITES=$(curl -s -u chicken:comfortable https://fluffy-knowledge.localsite.io/wp-json/custom/v1/acf | jq -r '.[]' | tr '\n' ' ')
          echo "SITES=$SITES" >> $GITHUB_ENV
          echo "Sites to deploy: $SITES"

      - name: Update selected site repos
        run: |
          for site in $SITES; do
            echo "Updating $site..."
            git clone --recurse-submodules https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/sagar-savani-md/$site.git
            cd $site
            cd wp-content/plugins/common-plugin
            git checkout main
            git pull origin main
            cd ../../..
            git add wp-content/plugins/common-plugin
            git commit -m "Auto-update common plugin submodule"
            git push origin main
          done
